export const AUTH_SIGNUP = "AUTH_SIGNUP"
export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_FORGET_PASSWORD = "AUTH_FORGET_PASSWORD"
export const AUTH_VERiFY_REST_PASSWORD = "AUTH_VERiFY_REST_PASSWORD"
export const AUTH_REST_PASSWORD = "AUTH_REST_PASSWORD"
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS"
export const CREATE_REVIEW = "CREATE_REVIEW"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCTS_BY_SOLD = "GET_PRODUCTS_BY_SOLD"
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const ERROR = "ERROR"
export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
export const CREATE_BRAND = "CREATE_BRAND"
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const GET_SPECIFIC_SUBCATEGORY = "GET_SPECIFIC_SUBCATEGORY"
export const GET_LOGGED_USER = "GET_LOGGED_USER"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD"
export const WISHLIST = "WISHLIST"
export const LOGGED_USER_WISHLIST = "LOGGED_USER_WISHLIST"
export const EDIT_REVIEW = "EDIT_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const GET_REVIEW = "GET_REVIEW"
/*
* coupons
* */
export const GET_ALL_COUPONS = "GET_COUPONS"
export const GET_COUPON = "GET_COUPON"
export const CREATE_COUPON = "CREATE_COUPON"
export const EDIT_COUPON = "EDIT_COUPON"
export const DELETE_COUPON = "DELETE_COUPON"

export const GET_ALL_CARTS = "GET_ALL_CARTS"
export const APPlY_COUPON_CART = "APPlY_COUPON_CART"
export const CREATE_CART = "CREATE_CART"
export const EDIT_CART = "EDIT_CART"
export const DELETE_CART = "DELETE_CART"
export const CLEAR_CART = "CLEAR_CART"


/*ERRORS TYPES*/
export const AS_ERROR = "AS_ERROR"
export const AL_ERROR = "AL_ERROR"
export const AF_ERROR = "AF_ERROR"
export const AV_ERROR = "AV_ERROR"
export const AR_ERROR = "AR_ERROR"
export const RG_ERROR = "RG_ERROR"
export const RC_ERROR = "RC_ERROR"
export const CG_ERROR = "CG_ERROR"
export const CC_ERROR = "CC_ERROR"
export const PD_ERROR = "PD_ERROR"
export const PE_ERROR = "PE_ERROR"
export const PG_ERROR = "PG_ERROR"
export const PGS_ERROR = "PGS_ERROR"
export const PGC_ERROR = "PGC_ERROR"
export const PC_ERROR = "PC_ERROR"
export const PG1_ERROR = "PG1_ERROR"
export const BG_ERROR = "BG_ERROR"
export const BC_ERROR = "BC_ERROR"
export const SC_ERROR = "SC_ERROR"
export const SG1_ERROR = "SG1_ERROR"
export const LUG_ERROR = "LUG_ERROR"
export const UG_ERROR = "UG_ERROR"
export const UCP_ERROR = "UCP_ERROR"
export const W_ERROR = "W_ERROR"
export const WLU_ERROR = "WLU_ERROR"
export const RE_ERROR = "RE_ERROR"
export const RD_ERROR = "RD_ERROR"
export const RG1_ERROR = "RG1_ERROR"
/*
* coupons
* */
export const COG_ERROR = "COG_ERROR"
export const COG1_ERROR = "COG1_ERROR"
export const COC_ERROR = "COC_ERROR"
export const COE_ERROR = "COE_ERROR"
export const COD_ERROR = "COD_ERROR"
/*
* cart
* */
export const CAG_ERROR = "CAG_ERROR"
export const CAAC_ERROR = "CAAC_ERROR"
export const CAC_ERROR = "CAC_ERROR"
export const CAE_ERROR = "CAE_ERROR"
export const CAD_ERROR = "CAD_ERROR"
export const CACL_ERROR = "CACL_ERROR"
